version: "3.4"
services:
  discord-bot-police:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      BUSCEMI_ID: "794074793388408832"
      DAFOE_CHANNEL_ID: "879574896139714611"
      DISCORD_TOKEN: ${discord-bot-police_DISCORD_TOKEN}
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
      FOW_ID: "806103358615977984"
      KNOWN_COMMUNIST_ID: "255261917348626432"
      PIZZAGATE_ID: "805388876511313931"
      SERVER_ID: "695565659303706745"
      SIMP_ID: "258174326581362689"
    image: discord-bot-police
    labels:
      ecs-local.secret.DISCORD_TOKEN: DISCORD_TOKEN
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: /Users/robekoc/projects/personal/discord-bot-police/task-definition.json
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-group: ecs
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: discord-bot-police
    networks:
      ecs-local-network: null
networks:
  ecs-local-network:
    external: true
