AWSTemplateFormatVersion: 2010-09-09
Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      TableName: DiscordUsers
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
